DEFINE get:refresh "0" DEFINE get:soft "replace"PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name ?prsn WHERE {
  ?prsn <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person>.
  ?prsn <http://xmlns.com/foaf/0.1/name> ?name.
  ?prsn <http://xmlns.com/foaf/0.1/mbox_sha1sum> ?checksum.
  ?prsn <http://purl.org/dc/elements/1.1/date> ?prsndate.
}
