DEFINE get:refresh "0" DEFINE get:soft "replace"PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT ?vndrlbl ?vndr WHERE {
  ?vndr <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Vendor>.
  ?vndr <http://www.w3.org/2000/01/rdf-schema#label> ?vndrlbl.
  ?vndr <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/country> ?country.
  ?vndr <http://purl.org/dc/elements/1.1/publisher> ?ublisher.
  ?vndr <http://purl.org/dc/elements/1.1/date> ?vndrdate.
}
